---
title: "Introduction to home range estimation (discrete methods)"
author: "Wenjing Xu 徐雯靓 (wenjing.xu@senckenberg.de)"
date: '`r format(Sys.time(), "%d %B %Y")`'
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: true
      smooth_scroll: true
    number_sections: false
    #theme: united
    #highlight: tango
pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) # display both code and results 
knitr::opts_chunk$set(fig.pos = 'H')
```

--------------------------------------------------------

# Introduction
Home range estimation is a foundational task in movement ecology, providing insights into the spatial extent and structure of an animal’s routine movements. While modern tracking technologies produce high-resolution movement data that are inherently autocorrelated, it is still common—and often useful—to apply discrete home range estimation methods that treat locations as independent. 

Discrete methods, such as Minimum Convex Polygons (MCP), Kernel Density Estimation (KDE), and Local Convex Hulls (LoCoH), offer a computationally straightforward and widely interpretable means of summarizing space use. They are especially valuable for rapid data exploration, comparative analysis across individuals or populations, and for generating intuitive visualizations of spatial behavior. 

In this session, we will focus on implementing MCP, LoCoH, and KDE using the `amt` package. 

In later sessions, we will address how to account for autocorrelation explicitly using advanced continuous-time movement modeling tools with `ctmm`. In fact, `amt` can also implement autocorrelated kernel density estimate (AKDE), which is a wrapper around `ctmm`. 

In this exercise, we will cover:

+ calculating MCP, KDE, and LoCoH for one individual with `amt`
+ calculating MCP, KDE, and LoCoH for multiple individuals with `amt`


## Load Libraries and data
Load the required libraries and remove everything held in [R's](https://cran.r-project.org/) memory.

```{r packages, warning=FALSE, message=FALSE, results='hide'}
library(tidyverse, quietly = TRUE) 
library(amt, quietly = TRUE) 
library(leaflet,quietly = TRUE)
library(RColorBrewer)  # for color palettes
library(sf)


# load data and filter out the unreliable locations
load("./Data/wildebeest_data.rdata")

WB <- WB %>%
  as_tibble() %>%
  filter(
    fixType == "3D" & as.numeric(DOP) < 10 | fixType == "2D" & as.numeric(DOP)  < 5)

```

Create tracks from the raw data: 
```{r track creation}
wb.trk <- make_track(WB, 
                            # tell the function which column contains the coordinates
                            .x = longitude, .y = latitude, 
                            # tell the function which CRS the coordinates are based on. 
                            crs = 4326, 
                            .t = timestamp,
                            # any additional information you want to attach to the track
                            # such as animal ID and month
                            id = animal_id, sex = sex, temp = temp) 

# because we want to calculate home range area in m2 or km2, 
# we will transform the data to projected coordinate system.
wb.trk.UTM <- transform_coords(wb.trk, 32737)

``` 


# Home range estimation with one individual
```{r amt filter to one }
# first we filter the data to the individual of interest
one.wb.trk.UTM <- wb.trk.UTM %>% filter(id == "Ole Nagol")
```


## MCP (Minimum Convex Polygon)

MCP creates polygon with the minimum area containing a certain percentage of the points. 

```{r MCP}
# estimate mcp at the level of 50% and 95%
one.wb.mcp <- hr_mcp(one.wb.trk.UTM, levels = c(0.5, 0.95))
plot(one.wb.mcp, main = paste("mcp")) 
```

MCP is a simple approach that assumes independence between observations and does not account for errors. It includes areas that maybe do not make sense and the intensity of space use is lost.

## LoCoH (Local Convex-Hull)
One step further from the simple MCP, LoCoH builds local MCP for each location with *k* neighbors, or in *r* radius, or in a *a* sum of distances. 


```{r locoh}

one.wb.locoh.20 <- hr_locoh(one.wb.trk.UTM, type = "k", n= 20, levels =  c(0.5, 0.95))
one.wb.locoh.50 <- hr_locoh(one.wb.trk.UTM, type = "k", n= 50, levels =  c(0.5, 0.95))
one.wb.locoh.100 <- hr_locoh(one.wb.trk.UTM, type = "k", n= 100, levels =  c(0.5, 0.95))

par(mfrow=c(1,3))
plot(one.wb.locoh.20, main = "k-locoh 5")
plot(one.wb.locoh.50, main = "k-locoh 50")
plot(one.wb.locoh.100, main = "k-locoh 100")
```

LoCoH takes into account that points are somewhat related and excludes the areas that are not used. However,  choosing k, r or a values in non-trivial (see the comparison above as an example), and it still assumes independence between observations and regular sampling.

## KDE (Kernel Density Estimation)
KDE calculates density of locations. Estimates the probability of encountering the animal given the _independence_ of sampling.

```{r KDE}
# Create a template raster for the KDE
trast <- make_trast(one.wb.trk.UTM, res = 50)
one.wb.kde <- hr_kde(one.wb.trk.UTM, trast = trast, levels = c(0.5, 0.95))
plot(one.wb.kde, main = "kde")
```

KDE still assumes independence between observations and regular sampling. Auto-correlation results in underestimating the area. Yet, these assumptions where not such a problem when data was scarce.

Note that argument `levels` in all these methods defines the isopleth levels used for calculating home ranges. Theoretically it is good to exclude points that are outliers, i.e. not typical of the individual's movement pattern or one-time forays into different areas. But sometimes such "outlier" behaviors are important. 

## calculating home range areas 

```{r mcp and kde and locoh for one wb - area}
hr_area_one_wb <- cbind(tibble(method = rep(c("mcp", "k-locoh 100", "kde"), each = 2)),
                        rbind(hr_area(one.wb.mcp), hr_area(one.wb.locoh.100), hr_area(one.wb.kde))) %>%
  select(-what)

hr_area_one_wb %>% ggplot(aes(x = method, y = area/1000000, #convert m2 to km2
                              group = factor(level), fill = factor(level))) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() + 
  ylab("area km^2")

```

Difference home range estimators may result in very different home range shapes and sizes. Locoh is the most conservation, while MCP might be too general. In addition, they often result in multi-part home ranges, while ecologically speaking, home range should not be fragmented (at least for terrestrial animals).

Ask yourself: does the method you choose serve your research goal? Are you look for a quick analysis to delineate a general area the animal could go to? Or you are looking for a conservation estimate to highlight the core areas that the animals heavily rely on?  


### Home range estimate for multiple individual

Calculting home range for all individuals in `amt` follows the same logic as how we calculate movement metrics for multiple individuals, except for step 3 because we are dealing with list of `sf` objects and we cannot simply unnest sf objects into a data frame. We will use MCP as an example here. 

```{r mcp_all_ind, warning=FALSE}

# step 1: nest the track by id

wb.trk.nested <- wb.trk.UTM %>% nest(data = -"id")

# step 2: calculate mcp 

wb.trk.nested <- wb.trk.nested %>% mutate(mcp = map(data, function(x) {
    mcp = hr_mcp(x, levels = 0.95)
    return(mcp$mcp)
    }
  ))

# step 3: combine mcp of multiple individuals to one sf object

wb.mcp <- bind_rows(wb.trk.nested$mcp) %>% mutate (id = wb.trk.nested$id)

wb.mcp

```


|           <span style="color:tomato">**TASK 1: ** make a bar plot to compare HR sizes across all individuals directly. What could be some reasons that the home range sizes vary so much across individuals? Consider - a fair comparison would be to compare HR sizes based on tracks of the same duration.  </span>
<br/><br/>


```{r mcp area bar, eval = FALSE, echo = FALSE}

wb.mcp %>% ggplot() +
  # turn area from m^2 to km^2 for easier interpretation
  geom_bar(aes( x = id, y = as.numeric(area)/1000000), 
           stat = "identity") +
  theme_minimal() +
  labs (y = "Area (km^2)")

```


Now we can easily plot the MCP for all individuals: 

```{r all wb mcp}
p_mcp <-  ggplot() +
  geom_sf(data = wb.mcp, aes(color = id), fill = NA, alpha = 0.4, linewidth = 0.8) +
  theme_minimal()
p_mcp

```



Alternatively, we can create a leaflet map to interactively explore the home ranges:
```{r leaflet}
# leaflet only takes long-lat data, so we transform it back to epsg:4326

wb.mcp.geo <- wb.mcp %>% st_transform(crs = st_crs(4326))

pal <- colorFactor(
  palette = brewer.pal(length(unique(wb.mcp.geo$id)), "Set3"),
  domain = wb.mcp.geo$id
)

# Create leaflet map
leaflet(wb.mcp.geo) %>%
  addProviderTiles("CartoDB.Positron") %>%  # add a base map
  addPolygons(
    fillColor = ~pal(id),
    color = "black",
    weight = 1,
    opacity = 1,
    fillOpacity = 0.6,
    popup = ~paste("Animal ID:", id)
  ) %>%
  addLegend("bottomright", pal = pal, values = ~id, title = "Animal ID")
```



### Save the HR results in a data frame.  

Sometimes to report the result you need to export the data as a data frame. `sf` objects can be easily turn into a data frame as below:

```{r same results in a data frame}
wb.mcp.df <- st_drop_geometry(wb.mcp)
```




---------------------
**Further readings:**

Walter, W. David, Dave P. Onorato, and Justin W. Fischer. "Is there a single best estimator? Selection of home range estimators using area-under-the-curve." Movement Ecology 3 (2015): 1-11.

Noonan, Michael J., et al. "A comprehensive analysis of autocorrelation and bias in home range estimation." Ecological Monographs 89.2 (2019): e01344.



 <center> -----------------     (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧  THE END :･ﾟ･ﾟ     ------------------ </center>